To-Do List tasks application
Leon-Mbegera/To-Do-List pull request #1
Opened 2021-08-27 11:39 UTC by Leon-Mbegera

This is a useful tool in the form of an application to help its users personally arrange their daily/weekly tasks into lists/project.
- The todos can be assigned details e.g. title, description, due date, and priority status.
- the user is also given the ability to edit their todos, or even delete them.

2021-08-27 12:12 UTC, afanimartin requested changes
## changes required 🙏🏿 🙏🏿 🙏🏿 
Nice work on this project. You have done well in setting up the project.

### highlights 🌵 🌵 🌵 
- PR is well described
- Readme looks good

### changes 🔕 🔕 🔕 
- separate DOM logic from JS logic
- add necessary packages to the `package.json`. check comments.
- remove comments from the codebase. check comments.
- see comments for more suggestions
- I couldn't run the app because `webpack-dev-server` was not added to the `package.json` file. please fix the error.

### Martin Afani
#### Slack: whiz25

2021-08-27 12:12 UTC, afanimartin commented on src/index.js
> +// Loop thru each project and display it
Remove this and any other comments from the codebase. Try to write clean and readable code so you don't have to add comments to your code.

2021-08-27 12:12 UTC, afanimartin commented on src/index.js
> +const showProjects = () => {
This project comes after lessons on `Single Responsibility` and `Modules`. This module is responsible for DOM manipulation logic and JS business logic.
You need to separate DOM manipulation and JS logic. So move this function to the `project.js` module since it has logic directly related to the `project.js` module.

2021-08-27 12:12 UTC, afanimartin commented on src/index.js
> +// function to create a project card
Remove all comments

2021-08-27 12:12 UTC, afanimartin commented on src/index.js
> +const projectExists = (projectName) => {
Move this to the `project.js` module.

2021-08-27 12:12 UTC, afanimartin commented on src/index.js
> +showProjects();
Move this to the `project.js` module.

2021-08-27 12:12 UTC, afanimartin commented on src/index.js
> +const addProjectToLocalStorage = (newProject) => {
Move this to the `project.js` module.

2021-08-27 12:12 UTC, afanimartin commented on src/project.js
> +  getTodo = (todoTitle) => {
These functions are directly related to the `todo.js` module so move them there.

2021-08-27 12:12 UTC, afanimartin commented on src/index.js
> +const showTodos = (currentPrj, newTodoCreationForm) => {
Move this function to the `todo` module.

2021-08-27 12:12 UTC, afanimartin commented on src/index.js
> +const modifyTodo = (todo, showTodos, newTodoCreationForm) => {
This function should live in the `todo` module so move it there.

2021-08-27 12:12 UTC, afanimartin commented on src/index.js
> +const getProjectsFromLocalStorage = () => {
Move this to the `project` module.

2021-08-27 12:12 UTC, afanimartin commented on package.json
> +    "webpack-cli": "^4.8.0"
Add `webpack-dev-server` so one can run `npm run start` without the error: `sh: 1: webpack-dev-server: not found`

2021-08-27 15:45 UTC, Leon-Mbegera commented on package.json
> +    "webpack-cli": "^4.8.0"
Done.

2021-08-27 15:53 UTC, Leon-Mbegera commented on src/index.js
> +// Loop thru each project and display it
Removed all inline comments from my codebase, so that it's clean and readable.

2021-08-29 09:02 UTC, Leon-Mbegera commented on src/index.js
> +// function to create a project card
All comments are now removed from the codebase.

2021-08-31 10:56 UTC, Leon-Mbegera commented on src/index.js
> +const getProjectsFromLocalStorage = () => {
Moved getProjectsFromLocalStorage function to dependency module.

2021-08-31 10:56 UTC, Leon-Mbegera commented on src/index.js
> +const modifyTodo = (todo, showTodos, newTodoCreationForm) => {
Moved modifyTodo to todo module.

2021-08-31 11:00 UTC, Leon-Mbegera commented on src/index.js
> +const showTodos = (currentPrj, newTodoCreationForm) => {
Moved showTodos to the todo module.

2021-08-31 11:03 UTC, Leon-Mbegera commented on src/project.js
> +  getTodo = (todoTitle) => {
Moved addTodo to the respective module.

2021-08-31 11:08 UTC, Leon-Mbegera commented on src/index.js
> +const showProjects = () => {
Separated logic between the modules.

2021-08-31 11:09 UTC, Leon-Mbegera commented on src/index.js
> +showProjects();
Moved showProjects to project.js

2021-08-31 11:10 UTC, Leon-Mbegera commented on src/index.js
> +const projectExists = (projectName) => {
Moved projectExists to project.js

2021-08-31 11:12 UTC, Leon-Mbegera commented
In these requested changes, I have,
- Moved all public methods to their respective modules
- Added a dependency file to hold common functions and variables
- Modified local storage to record every addition, update or delete done on project todos.

2021-08-31 12:37 UTC, mahmoud717 approved these changes
### STATUS: APPROVED ✔️ ✔️ 

**hi @Leon-Mbegera**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

2021-08-31 13:03 UTC, merged